### PR TITLE
master-sc-943

### PR DESCRIPTION
**Pull request by sharonchoi**
https://github.com/sharonchoi/liferay-portal/pull/943

### CODE REVIEW

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
ci:retest

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by alejandrohdezma** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by sharonchoi** [comment]
closing: https://github.com/sharonchoi/liferay-portal/pull/955

**Pull request closed without merging**
