### PR TITLE
7.0.x-bw-51

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-28287
https://issues.liferay.com/browse/LRQA-28413

@sharonchoi The Workflow and CPRoles tests are fixed on https://github.com/brianchandotcom/liferay-portal/pull/44132

### CODE REVIEW

**Comment by brianwulbern** [comment]
@sharonchoi Rebased.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by sharonchoi** [comment]
SF for BWulbern/YHan:
-created a for loop to run through list of document types

@brianwulbern @Hanlf

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/44206

**Pull request closed without merging**
