### PR TITLE
LPS-52697 Use the right path

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
hi @sharonchoi, 

Can you check the failling test and send it to brian (or to me if there are bugs) once they are fixed??

Thx!!

**Comment by robertoDiaz** [comment]
FYI, we are going to remove a lot of elements of Media Gallery portlet, so a lot of portlets will not apply. Maybe we could plan how to handle this (maybe we should disable the  MGallery tests temporalily).

**Comment by robertoDiaz** [comment]
No failing test (the failing one was introduced yesterday) so I'm going to send this to brian :)

**Comment by sharonchoi** [comment]
ok

**Pull request closed without merging**
