### PR TITLE
LPS-62231 Pagination in MB

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @sharonchoi 

This adds pagination to Message Boards. The pagination is in the "More messages" format, so we don't have actual pages but we just ask for more comments. When the user clicks More Messages it will include more messages without refreshing the page, so it will keep adding more and more in the same page.

The idea is that in the future, in Site Administration, we will get rid of the "More comments" button and we will use infinite scroll so when the user reaches the bottom of the page we will automatically add more messages.

I don't know if this breaks any acceptance tests, I'm sending this to you just in case.

Thanks!

### CODE REVIEW

**Comment by sharonchoi** [comment]
@sergiogonzalez Test fix ticket filed here, in case tests fail: https://issues.liferay.com/browse/LRQA-21869

**Comment by sharonchoi** [comment]
@sergiogonzalez 61 posts later......I finally see the button, lol. 
61_posts_later

**Comment by sergiogonzalez** [comment]
Sorry @sharonchoi, I completely forgot to mention that there's a portal.property that allows to set the threshold for the minimun pagination elements. You can add this to your portal-ext.properties and it should paginate way earlier: discussion.comments.delta.value=5

This property will change in the future because right now is the same as the comments but I'd like to have 2 separate properties, one for comments and one for message boards, so we can have different thresholds.

Keep in mind that the number specified there doesn't mean that it will paginate at exactly the number of elements specified in that property. You can see the description of that property in portal.properties:

```
#
# Set the value for the minimum number of discussion comments to display
# before paginating. As we paginate based on top level comments, we may
# display more discussion comments than the specified value until we find a
# top level discussion comment.
#
```

It seems that this pull doesn't break any tests?

Thanks!

**Comment by sharonchoi** [comment]
No test fixes needed, will file a new automation test ticket to cover functionality.

Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/35553

**Comment by sharonchoi** [comment]
Resent and pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/35591

**Pull request closed without merging**
