### PR TITLE
LPS-62466 Show "This page does not exist yet. Use the form below to create it " only when de page is new but has a title (we are triying to access to a inexistent page)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
hey @sharonchoi, can you check ir there are broken test in this pull??

thx!!

**Comment by sharonchoi** [comment]
@robertoDiaz ok will do

**Comment by sharonchoi** [comment]
@robertoDiaz are your changes supposed to remove a message? or add a message? the poshi tests are failing because the tests are failing to find an info message/alert that says "This page does not exist yet. Use the form below to create it."

**Comment by robertoDiaz** [comment]
Yep, I removed this message.

Please see https://issues.liferay.com/browse/LPS-62466 for details ;)

Thx @sharonchoi!!!

**Comment by sharonchoi** [comment]
Pushed to RDiaz:
https://github.com/robertoDiaz/liferay-portal/pull/375

**Comment by sharonchoi** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/35087

**Pull request closed without merging**
