### PR TITLE
master-qa-19932

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-19932

### CODE REVIEW

**Comment by sharonchoi** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
SF for AChiang:
-not sure why one of the pr tests failed, but I sent in a fix for that

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/32950

**Pull request closed without merging**
