### PR TITLE
LPS-XXXXX Fix knowledge base functional tests

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
hi @sharonchoi 

We've been fixing the broken functional tests we've seen in https://testray.liferay.com/home/-/testray/components/783387/details?_1_WAR_testrayportlet_testrayRunId=45807929

Could you please rerun the tests using the pr and generate a new report??

If everithing is right in this pr there will only be 2 broken test:

KnowledgebaseUsecase#ViewImportedKBArticleWithSourceURLMetadata
KnowledgebaseUsecase#ViewKBArticleGitHubSourceURL

That should be fixed in a different way (we are discussing  if we should upgrade to the new configuration api so you could change it via UI)

**Comment by sharonchoi** [comment]
@robertoDiaz Oh wow! Thanks! We'll be sure to take a look and keep you guys updated.

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/39604

**Pull request closed without merging**
