### PR TITLE
master-qa-21419

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-21419

### CODE REVIEW

**Comment by austinchiang** [comment]
@sharonchoi @patriciajeanperez @nikki-pru

The logic for this restructure is as follows:
- WikiTable.path will include all locators that pertain to the Wiki table in the site page
- Eventually we will have to come up with a place to store Wiki table lexicon view locators (i.e. descriptive, list). I am leaving that in Wiki.path for now
- In an attempt to move away from putting all other locators in Wiki.path, I have created WikiEntry.path
- WikiEntry.path should eventually include all locators you could find in a wiki entry (when adding, editing, and viewing). This aims to mirror BlogsEntry.path
- Some unused paths and macros have been deprecated

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
SF for AChiang:
source formatter caught some things

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/36741

**Pull request closed without merging**
