### PR TITLE
master-qa-20127

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-20127
https://issues.liferay.com/browse/LRQA-20138
https://issues.liferay.com/browse/LRQA-20353
cc: @alee8888

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/33846

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/33846

**Pull request closed without merging**
