### PR TITLE
master-qa-27530

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-27530

### CODE REVIEW

**Comment by ctampoya** [comment]
@sharonchoi This is a Forms pull from my developers (https://github.com/ctampoya/liferay-portal/pull/11). I have test fix commits added to it =) 

cc @rafaprax @marcellustavares @vicnate5

**Comment by ctampoya** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/42967
@vicnate5 @ctampoya @rafaprax @marcellustavares

**Pull request closed without merging**
