### PR TITLE
LPS-67019, LRQA-29906 | master

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LPS-67019
https://issues.liferay.com/browse/LRQA-29906

### CODE REVIEW

**Comment by nikki-pru** [comment]
This PR is only needed for master. Please do not backport

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/45818

**Pull request closed without merging**
