### PR TITLE
master-bw-51

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-28287
https://issues.liferay.com/browse/LRQA-28413

@sharonchoi I'm not sure what priority you want the new test at, so I kept it at 5.

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@sharonchoi Rebased.

**Comment by sharonchoi** [comment]
SF for BWulbern/YHan:
-created a for loop to run through list of document types

@brianwulbern @Hanlf

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/44205

**Pull request closed without merging**
