### PR TITLE
LPS-68142 XSS

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Sharon,

It seems this pull also breaks some functional tests in Announcements.
Could you please take a look at them?

Thx!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by sharonchoi** [comment]
Sure, will do.

**Comment by sergiogonzalez** [comment]
Thx 👍

**Comment by sharonchoi** [comment]
@sergiogonzalez test fixes will be worked on here: https://issues.liferay.com/browse/LRQA-27847

Also, quick question, did you guys update Announcements portlet to use Alloy Editor? Or is it just a new UI with the Configuration panel? The technical task ticket wasn't that descriptive, in what the intended behavior is supposed to look like.

**Comment by sergiogonzalez** [comment]
Hey @sharonchoi ,

Yeah, you're totally right. I'm gonna update the ticket description to include more information about the change.

Thx!

**Comment by sharonchoi** [comment]
@sergiogonzalez Am I supposed to be able to see the `<p>` tags when editing the content of an announcements entry? Or no?

announcements_edit_entry

**Comment by sergiogonzalez** [comment]
Thanks for the update @sharonchoi 

@4lejandrito is working on it 👍

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by sergiogonzalez** [comment]
Hey @sharonchoi we have sent a new pull here https://github.com/sharonchoi/liferay-portal/pull/896

I'm closing this one in favour of the other.

Thanks 😄

**Comment by 4lejandrito** [comment]
I closed https://github.com/sharonchoi/liferay-portal/pull/896  because it had conflicts which I solved and submitted in https://github.com/sharonchoi/liferay-portal/pull/897.

**Comment by sharonchoi** [comment]
thanks @sergiogonzalez @4lejandrito :)

**Pull request closed without merging**
