### PR TITLE
master-qa-21240

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-21240

### CODE REVIEW

**Comment by austinchiang** [comment]
@sergiogonzalez this should fix the failing tests from https://github.com/sharonchoi/liferay-portal/pull/372

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed tests to SGonzalez:
https://github.com/sergiogonzalez/liferay-portal/pull/2816

@sergiogonzalez There's a compile error at head on master, so I pushed Austin's test fixes to you, so you can submit to BChan after master works at head.

**Pull request closed without merging**
