### PR TITLE
LRQA-31707 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-31707

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:open

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Pushed tests back to AChiang: @austinchiang 
1) Please double check actual tests' functionalities, and do not remove tests that don't actually have duplicate functionality, ex: PGDocumentsandmedia#AddDocument
2) Please make each commit, one testcase command
3) Please add missing assertions from removed tests into covered tests' functionality
4) Please double check stability of covered tests on testray, before removing, ex: sharepoint/documentum tests

**Pull request closed without merging**
