### PR TITLE
master-qa-31701

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-31701

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop This test appears to be frozen.

**Comment by pyoo47** [comment]
ci:retest

**Comment by austinchiang** [comment]
@sharonchoi The Wiki smoke test, unlike Blogs and Message Boards, goes to system settings to configure CKEditor because there are no available properties to set in portal.properties.

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/48535

**Pull request closed without merging**
