### PR TITLE
master-qa-26918

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-26918

### CODE REVIEW

**Comment by austinchiang** [comment]
@sharonchoi  This is the image editor smoke test. Let's get some passing runs with it in CI first before adding it to the PR tester.

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/42105
https://github.com/brianchandotcom/liferay-portal/pull/42106

**Pull request closed without merging**
