### PR TITLE
LPS-68550 Change to protected

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Please, send it to Brian when you guys are done with the tests so we can have this change in the release.
Thanks! 👍

### CODE REVIEW

**Comment by sharonchoi** [comment]
@ambrinchaudhary @sergiogonzalez I fetched this branch and ran our functional tests here: https://github.com/sharonchoi/liferay-portal/pull/944
Fixing tests/investigating failures on this ticket: https://issues.liferay.com/browse/LRQA-28747

Some questions:
1) Is the link to the breadcrumb (on the active folder) supposed to be removed?
The old HTML locator was: `//ul[contains(@class,'breadcrumb')]//a[contains(.,'KB Folder 1')]`

Now, the link is not there: 
new_breadcrumb_html

2) more questions to come.....

**Comment by sergiogonzalez** [comment]
Hey @sharonchoi 

We didn't change the behaviour of the knowledge base breadcrumb in that pull.

Actually, looking at other portlets, it seems that the breadcrumb behaviour changed everywhere. Now, the active folder is never a link. That is also happening in Documents and Media or Web Content. I guess that it was changed as part of another story.

Thanks!

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by ambrinchaudhary** [comment]
Rebased and resent here: https://github.com/sharonchoi/liferay-portal/pull/952

**Comment by jonmak08** [comment]
Hey @sergiogonzalez, @ambrinchaudhary, and @sharonchoi,

The breadcrumb was changed to match Lexicon's intended behavior (https://issues.liferay.com/browse/LPS-67941).  I made the change and sent it to @ealonso to review.  The final pull was sent to @anthony-chu at https://github.com/brianchandotcom/liferay-portal/pull/44230.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
I am not sure if @anthony-chu's changes (https://github.com/brianchandotcom/liferay-portal/pull/44230) updated the QA tests for knowledge base or not.

**Comment by anthony-chu** [comment]
@jonmak08 I had not made changes to the knowledge base tests as they are not run on our PR tester by default and did not show up. @sharonchoi can you see if applying the changes from brianchandotcom#44230 will get the knowledge base breadcrumbs to work?

**Pull request closed without merging**
