### PR TITLE
master-qa-26105

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-26105

### CODE REVIEW

**Comment by sharonchoi** [comment]
@austinchiang Microblogs#DeleteEntry has failed, can you take a look?

**Comment by austinchiang** [comment]
@sharonchoi  Looking into the failures.

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Closing pr, as there is a bug with microblogs instances appearing across multiple portal instances.
https://issues.liferay.com/browse/LPS-66986

**Pull request closed without merging**
