### PR TITLE
LPS-66359 Automatically namespace generated ID

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Sharon,

Can you take a look to see if we need to update some tests from the PR that this pull might break?

This is from Adolfo:

---

@sharonchoi It may be necessary to include back the changes you made in brianchandotcom@6b6b0cc

I haven't done it myself because I'm not 100% sure it can be used as is (this PR is quite different from the other one). Could you check and cherry pick the commit if necessary?

Thanks!

### CODE REVIEW

**Comment by sharonchoi** [comment]
@sergiogonzalez sure thing, will do.

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@adolfopa 
`TypeError: d.one(...) is null
http://localhost:8080/group/test1/~/control_panel/manage/-/site/settings?_com_liferay_site_admin_web_portlet_SiteSettingsPortlet_historyKey=&p_p_auth=YZGpANA9&_com_liferay_site_admin_web_portlet_SiteSettingsPortlet_redirect=http%3A%2F%2Flocalhost%3A8080%2Fgroup%2Ftest1%2F~%2Fcontrol_panel%2Fmanage%2F-%2Fsite%2Fsettings%3F_com_liferay_site_admin_web_portlet_SiteSettingsPortlet_historyKey%3D%26p_p_auth%3DYZGpANA9
Line 27`

I think a typeerror is thrown, after publishing certain things, and it's a little hard to narrow down the issue at the moment, because there are a variety of errors, all stemming from some kind of jsp change. 

Also did you see BChan's comment here? https://issues.liferay.com/browse/LPS-66359
https://github.com/brianchandotcom/liferay-portal/pull/41533

ezgif com-video-to-gif

**Comment by adolfopa** [comment]
@sergiogonzalez @sharonchoi Could anyone close this pull? I've included some fixes for the problem described by Sharon; see https://github.com/sharonchoi/liferay-portal/pull/772

**Pull request closed without merging**
