### PR TITLE
LPS-63508 Move lang keys

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey sharon, I think this solves the problem of the broken test in the rebase ( I had accidentaly delete a method) 

I've restore this methos and it seems to work as expected.

Could you push it to brian???

Thanks!!

**Comment by sharonchoi** [comment]
@robertoDiaz investigating poshi failures, some of them should be fixed here: https://github.com/brianchandotcom/liferay-portal/pull/37090
https://github.com/brianchandotcom/liferay-portal/pull/37093
https://github.com/brianchandotcom/liferay-portal/pull/37094

and there's a failure due to a potential bug: https://issues.liferay.com/browse/LPS-63906

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/37150

**Pull request closed without merging**
