### PR TITLE
LPS-62253 Format source

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @sharonchoi 

This pull applies lexicon to Document Types view in Documents and Media and we change the interaction so instead of displaying Document Types and Metadata Sets in a dialog they are displayed integrated in the portlet (so no dialog anymore)

Let us know if you have any doubt about this

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by sharonchoi** [comment]
Test fix ticket here: https://issues.liferay.com/browse/LRQA-21875 @sergiogonzalez @robertoDiaz

**Comment by sergiogonzalez** [comment]
Hey @sharonchoi are the tests green for real? :)

**Comment by sharonchoi** [comment]
@sergiogonzalez yes.

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/35508

Test fixes will be sent in separate pull, since pr-tester is passing.

**Pull request closed without merging**
