### PR TITLE
master-qa-28283

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-28283

### CODE REVIEW

**Comment by ctampoya** [comment]
@sharonchoi This test is for master only. 
@marcellustavares Here is the Forms POSHI test for [LPS-68377](https://issues.liferay.com/browse/LPS-68377)

cc @alee8888 @xbrianlee I added a way to add role permissions for Forms in  684bd4b & f8ed16e

**Comment by marcellustavares** [comment]
Thx @ctampoya

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/43915

**Pull request closed without merging**
