### PR TITLE
master-qa-28522

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-28522

### CODE REVIEW

**Comment by austinchiang** [comment]
@sharonchoi This is a master-only fix. The UI for Message Boards reply is different on ee-7.0.x.

/cc @anthony-chu

**Comment by brianwulbern** [comment]
@sharonchoi @austinchiang should we use the LPS that caused the UI change in the commit message, so when it gets backported to 7.0, it will be fixed there too?  Or is this not going to be backported? :)

**Comment by sharonchoi** [comment]
@austinchiang why is this fix for master only? Is there a LPS ticket associated with this test fix?

**Comment by austinchiang** [comment]
@brianwulbern @sharonchoi I will commit this fix under LPS-60033.

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/44525

**Pull request closed without merging**
