### PR TITLE
master-qa-28522

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-28522

### CODE REVIEW

**Comment by austinchiang** [comment]
@sharonchoi This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/44525.

This is a master-only fix. See comments in https://github.com/sharonchoi/liferay-portal/pull/949

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/45207

**Pull request closed without merging**
