### PR TITLE
master-qa-29044

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-29044

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
@sharonchoi 
- I wrote this test in site administration so we have coverage for Mediawiki there (I think all of our custom format wiki tests are executed in the site page)
- I discovered https://issues.liferay.com/browse/LPS-69286 when working on this ticket which prevents me from running a completely green test
- To get the test reports you see in the LRQA, I replaced the Mediawiki-specific syntax (i.e. `''MediaWiki Child Page Content''`) with normal text (i.e. `MediaWiki Child Page Content`). I ran this to make sure the test steps after the blockage work, but I submitted the test with the Mediawiki-specific syntax.

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/45097

**Pull request closed without merging**
