### PR TITLE
LPS-62643 Display the lexicon icon when there's no thumbnail and don't display if there's no preview

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Sharon,

As we talked, this is a resent of https://github.com/brianchandotcom/liferay-portal/pull/35113
It was a rebase error in the Breaking Changes file. 

If for any reason threre's another rebase error feel free to work without rebasing and then send it to me and I'll deal with the rebase.

Thanks!

### CODE REVIEW

**Comment by sharonchoi** [comment]
yep, sounds good, yeah that's what I've been doing @sergiogonzalez

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
thx @sharonchoi

**Comment by sergiogonzalez** [comment]
Closing in favor of https://github.com/sharonchoi/liferay-portal/pull/413

**Pull request closed without merging**
