### PR TITLE
LPS-60671 There's no need to register this under IGPortletToolbarContributor since we don't need to reference this anywhere

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Sharon,

This pull should be the last one that I told you that should have a big impact on tests. 

We are removing the right panel in the Media Gallery. We are moving the actions to add images to the current folder to the portlet topper toolbar (we will keep it there in this portlet since we don't want to include more noise in the Media Gallery User Interface because the main purpose of this portlet is to make it look really nice and adding a toolbar of buttons it's not a good idea). 

Before this changes, users with permission could edit the current folder or even change the permission. Now this is something that is no longer possible and it should be done from the Documents and Media portlet. 

We know that this pull will break some tests so we are sending it to you guys now so you have more time to fix it.

If for any reason you guys fix it today (which we know it's very unlikely because it will break several tests and they don't seem to be easy fixes) please send it to us and not to Brian because we would like to remove some duplicated code in the backend before it gets merged. 

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by sharonchoi** [comment]
Test fix ticket filed here: https://issues.liferay.com/browse/LRQA-22124

@sergiogonzalez, will do, thanks!

**Comment by sharonchoi** [comment]
Hey @sergiogonzalez,

I think I found a bug, where an entry/document within a file/folder will not display. Is this intended?
Steps to reproduce:
1) Add a folder in MG
2) Add a document/picture inside folder
3) Click inside MG folder to view document/picture

no_image_inside_mg_folder

no_image_in_folder

**Comment by sergiogonzalez** [comment]
Yeah, that seems like a bug. @robertoDiaz can you take a look at it?

**Pull request closed without merging**
