### PR TITLE
master-qa-20516

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-20516

### CODE REVIEW

**Comment by sharonchoi** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/34185

**Pull request closed without merging**
