### PR TITLE
master-qa-17889

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-17889

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
I restarted this test on 10/15/15 at 12:21pm.

**Comment by sharonchoi** [comment]
Pushed tests back to AChiang:
-please make commits more logical
-please run affected tests in portal from changes

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/31174

**Pull request closed without merging**
