### PR TITLE
master-qa-22100

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-22100

### CODE REVIEW

**Comment by austinchiang** [comment]
@sharonchoi There appears to be a glitch when I run PGMediagallery#AddSubfolders that causes the test to fail because it does not click on the "Add Subfolder" menuitem when it tries adding a second subfolder. This does not seem to be related to the test logic. Could you try running this test with my commits to make sure it passes? Thanks!

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/36032

**Comment by sharonchoi** [comment]
@austinchiang will not push in this test fix, since test seems to be failing for unknown reason. Will wait for roberto's pull here: https://github.com/robertoDiaz/liferay-portal/pull/388 to fix issue.

**Pull request closed without merging**
