### PR TITLE
LPS-52697 Use Lexicon in media gallery (first pull)

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hey @sharonchoi, 

This is the rebased pr, If there are no broken test could you push it to Brian??

Thx!!

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Closing to update (Real bugs)

**Comment by robertoDiaz** [comment]
Reopen with the problem (I guess) fixed.

**Comment by austinchiang** [comment]
Hey @robertoDiaz , I am looking into why there are failing tests. There are some tests failing from CI that passe locally.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
