### PR TITLE
master-qa-25670

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-25670

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40441

**Pull request closed without merging**
