### PR TITLE
master-qa-27212

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-27212

### CODE REVIEW

**Comment by austinchiang** [comment]
@sharonchoi  @alee8888 [This commit](https://github.com/sharonchoi/liferay-portal/pull/837/commits/4571d22d45926460a44d79bfba03d7624bd980c6) rewrites the user teardown macro so it is not hardcoded with one user. Please let me know if this is okay!

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/42614

**Pull request closed without merging**
