### PR TITLE
LPS-62701 Display info bar only when the page already exists

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by sharonchoi** [comment]
Test fix ticket created here: https://issues.liferay.com/browse/LRQA-21996
Please expect a 1-3 turnaround.

**Comment by sharonchoi** [comment]
Hey @robertoDiaz, it looks like the poshi tests are failing, because there's no success message generated after publishing a wiki page, which, is a bug. Do you mind taking a look at this, and pushing back, when you guys fix it? Thanks!

**Comment by robertoDiaz** [comment]
Hi Sharon, Ive retest it and success message appears as expected once te
page is published or saved as draft.

Dir you manually reproduce it?

How could I reproduce it?

**Comment by sharonchoi** [comment]
Hmm yeah, I manually reproduced it yesterday. Lemme rebase and build and try again.

**Comment by robertoDiaz** [comment]
Ok, if you could, please describe some steps

**Comment by sharonchoi** [comment]
@robertoDiaz 
1) Navigate to Site Admin > Wiki
2) Click Main node
3) Click Frontpage to add a wiki page
4) Click Publish

Ohhh ok, so it looks like, editing the default Frontpage that's already there, doesn't trigger a success message, but adding a new wiki page does.

no_success_message

**Comment by robertoDiaz** [comment]
Error found and fixed.

This is a kind of workaround, but will do the trick :p

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@robertoDiaz Did you just do a force push? I don't think CI will be able to take your new changes, can you send a new pr? Thanks!

Edit: Hmm nevermind, I'm just gonna fetch, close, and send to myself. Resent here: https://github.com/sharonchoi/liferay-portal/pull/441

**Comment by robertoDiaz** [comment]
Yes I push force changes.

It has work several times to me.

Anyway, im in a train traveling to Madrid so i do not have connection.

Could you get the branch and send the pr to yourself? Thanks

**Pull request closed without merging**
