### PR TITLE
LRQA-31707 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-31707

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
@sharonchoi Errors seem unrelated to pull

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/48163

-Added one new acceptance test, that was removed, please see pull for more info

**Pull request closed without merging**
