### PR TITLE
master-qa-25149

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-25149

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
ci:retest

**Comment by austinchiang** [comment]
@sharonchoi I am fixing the poshi errors

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
ci:stop

**Comment by sharonchoi** [comment]
SF for AChiang:
-added missing macro to descriptive view to XssUsecase#ViewRecycleBinNoXSS

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/40117

**Pull request closed without merging**
