### PR TITLE
LRQA-30061 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-30061

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
@sharonchoi Once this test passes enough times, we should add it to the pr-tester.

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/46116

**Pull request closed without merging**
