### PR TITLE
LPS-67116 Explicit pass the group 0 to the permission check

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @sergiogonzalez 

Hey @sharonchoi, since we are changing the Announcements/Alerts portlets interface, this pr breaks some functional test. Can you check them??

Thanks!!!

**Comment by sharonchoi** [comment]
@robertoDiaz Ok, will do!

**Comment by sergiogonzalez** [comment]
Hey @sharonchoi can you please make sure to update the LPS of every commit to LPS-67116? There are quite a few ticket with LPS-67730 which is wrong.
Thanks!

**Comment by sharonchoi** [comment]
@sergiogonzalez ok, will do. We'll be working on fixing this pull here: https://issues.liferay.com/browse/LRQA-27614

**Comment by sharonchoi** [comment]
Pushed to SChoi:
https://github.com/sharonchoi/liferay-portal/pull/877
@robertoDiaz @sergiogonzalez

**Pull request closed without merging**
