### PR TITLE
master-bw-39

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-27876
https://issues.liferay.com/browse/LRQA-28289

@sharonchoi see the 7.0.x pull here: https://github.com/sharonchoi/liferay-portal/pull/917 Thanks :)

### CODE REVIEW

**Comment by brianwulbern** [comment]
@michaelhashimoto @lesliewong92

CPRolesCPWebcontent and the Wiki tests fail from the VNC issue.  See my comment on: https://issues.liferay.com/browse/LRQA-28169

**Comment by brianwulbern** [comment]
@sharonchoi not sure why the XSS test failed, there might be a connection issue with Google Analytics.

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/43909

**Pull request closed without merging**
