### PR TITLE
master-qa-28837

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-28837

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Closing, please see comment on #951

**Comment by brianwulbern** [comment]
See 7.0.x here: https://github.com/sharonchoi/liferay-portal/pull/958
master here: https://github.com/sharonchoi/liferay-portal/pull/959

**Comment by brianwulbern** [comment]
See https://github.com/sharonchoi/liferay-portal/pull/960 for master commit under proper LPS message

**Pull request closed without merging**
