### PR TITLE
master-qa-27433

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-27433
https://issues.liferay.com/browse/LRQA-27434

### CODE REVIEW

**Comment by brianwulbern** [comment]
rebased

**Comment by brianwulbern** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/42935

**Pull request closed without merging**
