### PR TITLE
7.0.x-bw-47

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-28273

### CODE REVIEW

**Comment by brianwulbern** [comment]
@sharonchoi Rebased.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/44208

**Pull request closed without merging**
