### PR TITLE
LPS-60033, LRQA-29346 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LPS-60033
https://issues.liferay.com/browse/LRQA-29346

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
These changes are only for master. Please do not backport.

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan;
https://github.com/brianchandotcom/liferay-portal/pull/45951

**Pull request closed without merging**
