### PR TITLE
master-qa-16351

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-16351

### CODE REVIEW

**Comment by austinchiang** [comment]
Please refer to Brian's comment here: https://github.com/brianchiu/liferay-portal/pull/836

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChiu:
https://github.com/brianchiu/liferay-portal/pull/857

**Pull request closed without merging**
