### PR TITLE
master-qa-18394

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-18394

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Pushed tests back to AChiang:
-please check other permissions tests

**Comment by austinchiang** [comment]
Took out an obsolete commit because LRQA-18336 has taken care of it.

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChiu:
https://github.com/brianchiu/liferay-portal/pull/854

**Pull request closed without merging**
