### PR TITLE
LPS-63225 Toggle the info panel in DM in file entry details view

### PR DESCRIPTION
**Pull request by robertoDiaz**
hi @sharonchoi .

If everything is ok, could you push this to Brian??

Thanks!!!!

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @sergiogonzalez, see https://github.com/sharonchoi/liferay-portal/commit/f60b1f7bfe7e87c4092fd015eeee500ef23bfc70

**Comment by sharonchoi** [comment]
Test fix ticket filed here: https://issues.liferay.com/browse/LRQA-22331

**Comment by nikki-pru** [comment]
ci:retest

**Comment by nikki-pru** [comment]
Changes submitted here: https://github.com/sharonchoi/liferay-portal/pull/482

**Pull request closed without merging**
