### PR TITLE
LRQA-29964 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-29964

### CODE REVIEW

**Comment by austinchiang** [comment]
@sharonchoi I did not run this test locally because the UI of the Twitter post will change from `19h` to `December 28` a few days from now. The test will (continue to) fail now but should pass in a few days. Please let me know if this is okay, or if we should wait before pushing these changes in. Thanks! ☃️ 

# **Twitter UI**
twitter

============
# **Liferay UI**

liferay

**Comment by austinchiang** [comment]
@sharonchoi  I've removed the assertion for the date in the Twitter test.

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/45945

**Pull request closed without merging**
