### PR TITLE
master-qa-19263

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-19263
https://issues.liferay.com/browse/LRQA-19273

### CODE REVIEW

**Comment by sharonchoi** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
@sharonchoi This pull will be combined with https://github.com/sharonchoi/liferay-portal/pull/211

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/32357

**Pull request closed without merging**
