### PR TITLE
master-qa-28191

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-28191

### CODE REVIEW

**Comment by ctampoya** [comment]
@sharonchoi I added a POSHI test on top of my devs' commits. If you could please prioritize this pull that would be great. We are trying to get these commits merged into master ASAP. Thanks!

cc @marcellustavares

**Comment by marcellustavares** [comment]
Thanks @ctampoya :)

**Comment by sharonchoi** [comment]
SF for CTampoya:
-updated assertions in macro FormFields#viewDateFieldNotPresent to assertNotVisible, as element is present on page
-updated value of fieldName
@ctampoya

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/43833

**Pull request closed without merging**
