### PR TITLE
master-bw-12

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-27170

@sharonchoi these changes look fine to me, let me know if you want to fix these tests in a different way.

I'm aware of the conversation on https://github.com/brianchandotcom/liferay-portal/pull/41510 and https://github.com/brianchandotcom/liferay-portal/pull/41831, about the story [LPS-60033](https://issues.liferay.com/browse/LPS-60033).

Since I'm not sure what's coming down the pipeline for LPS-60033 (esp since part of it is still in [review](https://issues.liferay.com/browse/LPS-66968)) I'll leave the decision to you on whether to backport these commits to 7.0.x.

Thanks!

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Pushed tests back to BWulbern:
@brianwulbern Please remove the 2nd commit and re-send, we will not be updating Message Boards to use AlloyEditor on ee-7.0.x.

**Comment by brianwulbern** [comment]
Thanks for checking before my Monday!  Resent here: https://github.com/sharonchoi/liferay-portal/pull/845

**Comment by sharonchoi** [comment]
Yeah, no problem, if you can send the 2nd commit in a separate pull, that'd be great, thanks! @brianwulbern

**Comment by brianwulbern** [comment]
Sure thing, here's the pull: https://github.com/sharonchoi/liferay-portal/pull/850

**Pull request closed without merging**
