### PR TITLE
LPS-71482 Upgrade to OpenCMIS 0.14

### PR DESCRIPTION
**Pull request by adolfopa**
Hey Sharon,

I've upgraded the OpenCMIS libraries to version 0.14, as there is a bug in 0.13 that is affecting some clients.

Do the Alfresco tests execute automatically with each PR? If that's so, feel free to close this and I'll send it to Brian. Otherwise, could you guys run the tests to see if this breaks anything?

Thanks!

### CODE REVIEW

**Comment by sharonchoi** [comment]
hey @adolfopa,

I'm sorry to say this, but we don't have automated tests for Alfresco....we've never been able to get a hold of that environment for some reason from IT, so we were never able to automate it. Nevertheless, I'll take a look, and do some manual testing for this pull.

Thanks!

**Comment by adolfopa** [comment]
Thanks a lot @sharonchoi !

**Comment by sharonchoi** [comment]
@adolfopa : https://issues.liferay.com/browse/LPS-71769 is blocking me from testing this pull on master, potentially

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48448

I've tested this after checking https://issues.liferay.com/browse/LPS-71769 and everything works fine.

**Pull request closed without merging**
