### PR TITLE
LPS-69364, LRQA-29802 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LPS-69364
https://issues.liferay.com/browse/LRQA-29802

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
These changes are for master only. Please do not backport, thanks!

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by sharonchoi** [comment]
No test changes needed :)

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/46070

**Pull request closed without merging**
