### PR TITLE
LPS-63117

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @sharonchoi,

This will need poshi fixes, since the title of the element has changed. Not sure if you prefer to add the `data-qa-id` attribute or change the locator...

Thanks!

### CODE REVIEW

**Comment by sharonchoi** [comment]
Test fix ticket filed here: https://issues.liferay.com/browse/LRQA-22155

Please expect a 1-3 day turnaround.

**Comment by sharonchoi** [comment]
Pushed to SChoi:
https://github.com/sharonchoi/liferay-portal/pull/459

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/36122

**Comment by jbalsas** [comment]
Thanks a lot, Sharon! :relaxed:

**Pull request closed without merging**
